services:
  
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-measures}
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    restart: always
    command: pnpm run start:dev
    depends_on:
      - db
    links:
      - db
    environment:
      PORT: "80"
      DB_HOST: "db"
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASS:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-measures}

volumes:
  db:
    driver: local
